-- V105__Document_Signature_Folders_Schema.sql

ALTER TABLE documents ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS confirmed_ip VARCHAR(45) DEFAULT NULL;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS folder VARCHAR(128) DEFAULT 'Разное';
