-- 1. Add status to courses
ALTER TABLE courses ADD COLUMN status VARCHAR(32) NOT NULL DEFAULT 'DRAFT';
UPDATE courses SET status = 'PUBLISHED' WHERE is_published = TRUE;
ALTER TABLE courses DROP COLUMN is_published;

-- 2. Create chapters table
CREATE TABLE chapters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    order_index INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Migrate existing lessons to chapters
-- Create a default chapter for each existing course
INSERT INTO chapters (course_id, title, order_index)
SELECT DISTINCT id, 'Основной модуль', 0 FROM courses;

-- Add chapter_id to lessons
ALTER TABLE lessons ADD COLUMN chapter_id BIGINT;

-- Update lessons with the chapter_id of their course
UPDATE lessons
SET chapter_id = (SELECT c.id FROM chapters c WHERE c.course_id = lessons.course_id LIMIT 1);

-- Make chapter_id NOT NULL and add foreign key
ALTER TABLE lessons ALTER COLUMN chapter_id SET NOT NULL;
ALTER TABLE lessons ADD CONSTRAINT fk_lessons_chapter FOREIGN KEY (chapter_id) REFERENCES chapters(id) ON DELETE CASCADE;

-- 4. Create lesson_blocks
CREATE TABLE lesson_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL,
    order_index INTEGER NOT NULL DEFAULT 0,
    content TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Migrate old lesson content/file to lesson_blocks
INSERT INTO lesson_blocks (lesson_id, type, order_index, content)
SELECT id, 
       CASE 
           WHEN type = 'VIDEO' THEN 'VIDEO' 
           WHEN type = 'DOCUMENT' THEN 'FILE' 
           ELSE 'TEXT' 
       END, 
       0, 
       CASE 
           WHEN file_path IS NOT NULL THEN CONCAT('{"url":"', file_path, '", "name":"', COALESCE(file_name, 'file'), '"}')
           ELSE content 
       END
FROM lessons
WHERE file_path IS NOT NULL OR content IS NOT NULL;

-- 5. Clean up lessons table
ALTER TABLE lessons DROP CONSTRAINT IF EXISTS lessons_course_id_fkey;
ALTER TABLE lessons DROP COLUMN course_id;
ALTER TABLE lessons DROP COLUMN content;
ALTER TABLE lessons DROP COLUMN file_path;
ALTER TABLE lessons DROP COLUMN file_name;
ALTER TABLE lessons DROP COLUMN content_type;
ALTER TABLE lessons DROP COLUMN file_size;
ALTER TABLE lessons ADD COLUMN duration_minutes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE lessons ADD COLUMN is_preview BOOLEAN NOT NULL DEFAULT FALSE;

-- 6. Create Enrollments and Progress tables
CREATE TABLE enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    enrolled_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_enrollment UNIQUE (course_id, user_id)
);

CREATE TABLE lesson_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    video_progress_seconds INTEGER NOT NULL DEFAULT 0,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_lesson_progress UNIQUE (lesson_id, user_id)
);

-- 7. Add Indices
CREATE INDEX idx_lesson_progress_user ON lesson_progress(user_id);
CREATE INDEX idx_lesson_progress_lesson ON lesson_progress(lesson_id);
CREATE INDEX idx_enrollment_user ON enrollments(user_id);
CREATE INDEX idx_chapter_course ON chapters(course_id, order_index);
CREATE INDEX idx_lesson_chapter ON lessons(chapter_id, order_index);
