CREATE TABLE app_users (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                           updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                           email VARCHAR(160) NOT NULL,
                           enabled BOOLEAN NOT NULL,
                           full_name VARCHAR(120) NOT NULL,
                           password_hash VARCHAR(255) NOT NULL,
                           role VARCHAR(32) NOT NULL CHECK (role IN ('ADMIN','EMPLOYEE','CLIENT')),
                           assigned_employee_id BIGINT,
                           PRIMARY KEY (id),
                           CONSTRAINT uk_app_users_email UNIQUE (email),
                           CONSTRAINT fk_app_users_assigned_employee FOREIGN KEY (assigned_employee_id) REFERENCES app_users (id) ON DELETE SET NULL
);

CREATE TABLE invoices (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                          updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                          amount NUMERIC(19, 2) NOT NULL,
                          status VARCHAR(32) NOT NULL CHECK (status IN ('DRAFT', 'PENDING', 'PAID', 'OVERDUE', 'CANCELLED')),
                          description VARCHAR(500),
                          client_id BIGINT NOT NULL,
                          created_by_id BIGINT NOT NULL,
                          PRIMARY KEY (id),
                          CONSTRAINT fk_invoices_client FOREIGN KEY (client_id) REFERENCES app_users (id) ON DELETE CASCADE,
                          CONSTRAINT fk_invoices_creator FOREIGN KEY (created_by_id) REFERENCES app_users (id) ON DELETE RESTRICT
);

CREATE TABLE primary_documents (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                   created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                                   updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                                   file_name VARCHAR(255) NOT NULL,
                                   file_storage_path VARCHAR(512) NOT NULL,
                                   document_type VARCHAR(64) NOT NULL,
                                   invoice_id BIGINT,
                                   uploaded_by_id BIGINT NOT NULL,
                                   PRIMARY KEY (id),
                                   CONSTRAINT fk_documents_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE SET NULL,
                                   CONSTRAINT fk_documents_uploader FOREIGN KEY (uploaded_by_id) REFERENCES app_users (id) ON DELETE RESTRICT
);

CREATE INDEX idx_app_users_email ON app_users (email);
CREATE INDEX idx_invoices_client ON invoices (client_id);
CREATE INDEX idx_documents_invoice ON primary_documents (invoice_id);