services:
  postgres:
    image: postgres:17-alpine
    container_name: zhan-finance-postgres
    environment:
      POSTGRES_DB: zhanfindb
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: pass1
    ports:
      - "5432:5432"
    volumes:
      - zhan-finance-postgres:/var/lib/postgresql/data

volumes:
  zhan-finance-postgres:
