/**
 * This file was auto-generated by openapi-typescript contract definition.
 * Do not make direct manual modifications unless regenerating from /api/v3/api-docs.
 */

export interface paths {
  "/api/v1/auth/login": {
    post: operations["login"];
  };
  "/api/v1/auth/register": {
    post: operations["register"];
  };
  "/api/v1/auth/refresh": {
    post: operations["refreshToken"];
  };
  "/api/v1/auth/logout": {
    post: operations["logout"];
  };
  "/api/v1/auth/me": {
    get: operations["getCurrentUser"];
  };
  "/api/v1/crm/tasks": {
    get: operations["getTasks"];
    post: operations["createTask"];
  };
  "/api/v1/billing/invoices": {
    get: operations["getInvoices"];
  };
  "/api/v1/billing/subscriptions": {
    get: operations["getSubscriptions"];
  };
  "/api/v1/admin/billing/receipts": {
    get: operations["getAdminReceipts"];
  };
}

export interface webhooks {}

export interface components {
  schemas: {
    ApiResponse: {
      success: boolean;
      data?: unknown;
      message?: string | null;
      timestamp: string;
      requestId?: string;
    };
    UserDto: {
      id: number;
      email: string;
      fullName: string;
      role: "ADMIN" | "EMPLOYEE" | "CLIENT" | "LEARNER" | "CURATOR" | "ADVISOR";
      enabled: boolean;
      locale?: string;
      twoFactorEnabled?: boolean;
    };
    TaskDto: {
      id: number;
      title: string;
      description?: string;
      status?: string;
      priority?: string;
      stageId?: number;
      clientId?: number;
      assignedEmployeeId?: number;
      createdAt?: string;
      updatedAt?: string;
    };
    PaymentReceiptDto: {
      id: string;
      clientId: number;
      amount: number;
      receiptUrl: string;
      status: "AWAITING_REVIEW" | "CONFIRMED" | "REJECTED";
      tariffPlan?: string;
      createdAt: string;
      reviewedAt?: string;
    };
    InvoiceDto: {
      id: number;
      number: string;
      amount: number;
      status: "DRAFT" | "SENT" | "PAID" | "CANCELED" | "OVERDUE";
      dueDate: string;
      clientId: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export interface operations {
  login: {
    requestBody: {
      content: {
        "application/json": {
          email: string;
          password?: string;
        };
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse"];
        };
      };
    };
  };
  register: {
    requestBody: {
      content: {
        "application/json": {
          fullName: string;
          email: string;
          password?: string;
          role?: string;
        };
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse"];
        };
      };
    };
  };
  refreshToken: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse"];
        };
      };
    };
  };
  logout: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse"];
        };
      };
    };
  };
  getCurrentUser: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse"];
        };
      };
    };
  };
  getTasks: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse"];
        };
      };
    };
  };
  createTask: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse"];
        };
      };
    };
  };
  getInvoices: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse"];
        };
      };
    };
  };
  getSubscriptions: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse"];
        };
      };
    };
  };
  getAdminReceipts: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse"];
        };
      };
    };
  };
}
